// unicode.go — Unicode Character Database plumbing. -gen-ranges regenerates
// tools/uniranges_gen.go from the latest UCD so the validator can check
// samples offline; fetchBlocks feeds -fill-pdfs.
package main

import (
	"fmt"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const ucdBase = "https://www.unicode.org/Public/UCD/latest/ucd/"

// ucdRange is one "XXXX..YYYY ; Value" line of a UCD data file.
type ucdRange struct {
	lo, hi rune
	val    string
}

var reUCDLine = regexp.MustCompile(`^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([^#;]+)`)

func parseUCDRanges(text string) []ucdRange {
	var out []ucdRange
	for _, line := range strings.Split(text, "\n") {
		m := reUCDLine.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		lo, _ := strconv.ParseUint(m[1], 16, 32)
		hi := lo
		if m[2] != "" {
			hi, _ = strconv.ParseUint(m[2], 16, 32)
		}
		out = append(out, ucdRange{rune(lo), rune(hi), strings.TrimSpace(m[3])})
	}
	return out
}

// ucdFileVersion extracts "17.0.0" from a header like "# Scripts-17.0.0.txt".
func ucdFileVersion(text string) string {
	m := regexp.MustCompile(`^#\s*\S+-(\d+\.\d+\.\d+)\.txt`).FindStringSubmatch(text)
	if m == nil {
		return "unknown"
	}
	return m[1]
}

// scriptAliases parses PropertyValueAliases.txt into long-name → ISO code
// (e.g. "Adlam" → "Adlm", "Inherited" → "Zinh").
func scriptAliases(text string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(text, "\n") {
		if !strings.HasPrefix(line, "sc ") && !strings.HasPrefix(line, "sc\t") {
			continue
		}
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		f := strings.Split(line, ";")
		if len(f) < 3 {
			continue
		}
		code := strings.TrimSpace(f[1])
		long := strings.TrimSpace(f[2])
		out[long] = code
	}
	return out
}

func fetchBlocks(c *http.Client) ([]ucdRange, error) {
	text, err := fetch(c, ucdBase+"Blocks.txt")
	if err != nil {
		return nil, err
	}
	return parseUCDRanges(text), nil
}

// runGenRanges fetches Scripts.txt + PropertyValueAliases.txt and rewrites
// tools/uniranges_gen.go with per-ISO-code code point ranges.
func runGenRanges(outPath string) int {
	client := newHTTPClient()

	aliasText, err := fetch(client, ucdBase+"PropertyValueAliases.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "fetch PropertyValueAliases.txt: %v\n", err)
		return 1
	}
	aliases := scriptAliases(aliasText)

	scriptsText, err := fetch(client, ucdBase+"Scripts.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "fetch Scripts.txt: %v\n", err)
		return 1
	}
	version := ucdFileVersion(scriptsText)

	byCode := map[string][]rng{}
	longNames := map[string]string{}
	for _, r := range parseUCDRanges(scriptsText) {
		code, ok := aliases[r.val]
		if !ok {
			fmt.Fprintf(os.Stderr, "warning: no ISO code for script name %q\n", r.val)
			continue
		}
		byCode[code] = append(byCode[code], rng{r.lo, r.hi})
		longNames[code] = r.val
	}

	codes := make([]string, 0, len(byCode))
	for c := range byCode {
		rs := byCode[c]
		sort.Slice(rs, func(i, j int) bool { return rs[i].lo < rs[j].lo })
		// merge adjacent/contiguous ranges
		merged := rs[:1]
		for _, r := range rs[1:] {
			last := &merged[len(merged)-1]
			if r.lo <= last.hi+1 {
				if r.hi > last.hi {
					last.hi = r.hi
				}
				continue
			}
			merged = append(merged, r)
		}
		byCode[c] = merged
		codes = append(codes, c)
	}
	sort.Strings(codes)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by \"go run ./tools -gen-ranges\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: Unicode Character Database Scripts.txt, version %s.\n", version)
	b.WriteString("package main\n\n")
	b.WriteString("// ucdVersion is the UCD release the table below was generated from.\n")
	fmt.Fprintf(&b, "const ucdVersion = %q\n\n", version)
	b.WriteString("type rng struct{ lo, hi rune }\n\n")
	b.WriteString("var scriptRanges = map[string][]rng{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t%q: {", c)
		for i, r := range byCode[c] {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "{0x%04X, 0x%04X}", r.lo, r.hi)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// scriptLongNames maps ISO codes to UCD Script property long names.\n")
	b.WriteString("var scriptLongNames = map[string]string{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t%q: %q,\n", c, longNames[c])
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		return 1
	}
	fmt.Printf("wrote %s: %d scripts, UCD %s\n", outPath, len(codes), version)
	return 0
}
